### PR TITLE
added optional limit param to uploadAll

### PR DESCRIPTION
**Pull request by darrenbritton**
also patched a failing test, not sure if it was a false positive or rightfully failing...

### CODE REVIEW

**Comment by CrockAgile** [comment]
I am stunned anyone stumbled upon this repository. And not only have you stumbled upon it, but your changes look great! As you probably noticed, I have not been maintaining this project at all. Your changes will be merged, but also let me know if you would like to adopt this project. I know it has a lot of work to be done, but I have not been in the javascript mindset for a while, and I believe if you find this code useful, then it is better off in your hands. Let me know what you think!

**Comment by darrenbritton** [comment]
yeah it a long story, but the gist is i'm doing some NLP for streaming of music from youtube and when a channel name was parsed it would encode the latest video from the channel to an mp3 and pipe it out.

I'm not a regular contributor but seeing how clean this module was, its better than half of the modules written today never mind a year ago, was encouraging. It seems a shame to lose you from the js community. But yes, I would be happy to adopt such cleanly constructed module. I have no idea what the process for adopting a module is though :) 

obligatory kerbal love:
kerbal

**Comment by CrockAgile** [comment]
Sorry for going quiet! Thanks again for your contribution. I am still a little fuzzy on the proper process for transferring ownership, but I found out I might be becoming more active in the github and js communities soon. Would having an actually active maintainer who updates their module be enough for your project?

**Comment by darrenbritton** [comment]
no worries :+1: in the meantime i have realized that what i'm after is something that massages the data a little to make it more consumable for general purpose use. something akin to the response produced by https://www.npmjs.com/package/youtube-search but specifically for channels. if you now intend to maintain this module i'd probably start working on a new module that consumes this module and produces something of that ilk. this would likely lead to occasional contributions to this module. Any thoughts?

**Comment by CrockAgile** [comment]
@ThatCrazyIrishGuy I am a little unfamiliar with `youtube-search`. Could you provide some example output and describe what attributes of its output you would like this or a parent module to mimic? If so, then we can make it happen! And good luck with your streaming project! Someday I'll have to take a look at it if it is open.

**Comment by darrenbritton** [comment]
hi, sorry, work's been crazy. this is the kind of output i'm after:

``` javascript/json
[
  {
    "id": "Mn69LJ0239E",
    "link": "https://www.youtube.com/watch?v=Mn69LJ0239E",
    "kind": "youtube#video",
    "publishedAt": "2013-01-28T14:13:47.000Z",
    "channelId": "UCIxhklro9nQVRMWGaW96gmA",
    "title": "Best of deadmau5 – Continuous Mix",
    "description": "Crank up your speakers and pop open a brew, it's time for deadmau5! If you love Joel Zimmerman, you'll definitely enjoy this playlist featuring some of his most ...",
    "thumbnails": {
      "default": {
        "url": "https://i.ytimg.com/vi/Mn69LJ0239E/default.jpg",
        "width": 120,
        "height": 90
      },
      "medium": {
        "url": "https://i.ytimg.com/vi/Mn69LJ0239E/mqdefault.jpg",
        "width": 320,
        "height": 180
      },
      "high": {
        "url": "https://i.ytimg.com/vi/Mn69LJ0239E/hqdefault.jpg",
        "width": 480,
        "height": 360
      }
    }
  }, ...
```

an api for channel that would return a simple array of objects. because we're only interested in videos the 'kind' field here could probably be omitted. but a similar method for playlists would probably be quite nice. i might get some time to pull something together on sunday.

edit: after looking at https://github.com/MaxGfeller/youtube-search/blob/master/index.js it seems this is just extracted from the results of the search api. if the channel api is similar this might be easier than initially expected.

**Pull request merged**
